version: '3.8'

services:
  # Serviço do MySQL
  db:
    image: mysql:8.0 
    container_name: ecom_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ecommercedb            
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password            
    ports:
      - "3307:3306"
    volumes:
        - ./init:/docker-entrypoint-initdb.d
        - db_data:/var/lib/mysql